import argparse
import pathlib
import re
import tomllib


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("version")
    parser.add_argument(
        "--version-file",
        default="src/version.py",
    )
    args = parser.parse_args()

    version = args.version

    if not re.fullmatch(
        r"[0-9]+\.[0-9]+\.[0-9]+"
        r"(?:[-+][0-9A-Za-z.-]+)?",
        version,
    ):
        raise SystemExit(f"Invalid release version: {version}")

    pyproject_path = pathlib.Path("pyproject.toml")

    with pyproject_path.open("rb") as file:
        data = tomllib.load(file)

    old_version = data.get("project", {}).get("version")
    if not isinstance(old_version, str):
        raise SystemExit(
            "pyproject.toml does not contain "
            "a static [project].version"
        )

    text = pyproject_path.read_text(encoding="utf-8")

    project_pattern = re.compile(
        r"(?ms)"
        r"(^\[project\]\s*$)"
        r"(.*?)"
        r"(^\[|\Z)"
    )
    project_match = project_pattern.search(text)

    if project_match is None:
        raise SystemExit("[project] section was not found")

    project_body = project_match.group(2)
    version_pattern = re.compile(
        r"""(?m)^version\s*=\s*["'][^"']*["']\s*$"""
    )

    if len(version_pattern.findall(project_body)) != 1:
        raise SystemExit(
            "Expected exactly one version in [project]"
        )

    updated_body = version_pattern.sub(
        f'version = "{version}"',
        project_body,
        count=1,
    )

    updated_text = (
        text[:project_match.start(2)]
        + updated_body
        + text[project_match.end(2):]
    )

    pyproject_path.write_text(
        updated_text,
        encoding="utf-8",
    )

    version_path = pathlib.Path(args.version_file)
    version_path.parent.mkdir(parents=True, exist_ok=True)
    version_path.write_text(
        '"""Generated by the release workflow."""\n\n'
        f'__version__ = "{version}"\n',
        encoding="utf-8",
    )

    print(f"Injected version {version}")


if __name__ == "__main__":
    main()
